version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - mluk
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes_from: 
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: dqilyf@gmail.com
    networks: 
      - mluk
      
  pixiv:
    image: nginx:alpine
    container_name: pixiv
    ports:
      - 81:8000
    volumes:
      - /home/pixiv:/usr/share/nginx/html:ro  
    environment:
      VIRTUAL_HOST: pixiv.mluk.top
      LETSENCRYPT_HOST: pixiv.mluk.top
    networks: 
      - mluk

  hibiapi:
    image: hibiapi
    container_name: api
    ports:
      - 88:8080
    environment:
      VIRTUAL_HOST: api.mluk.top
      LETSENCRYPT_HOST: api.mluk.top
    networks:
      - mluk  

networks:
  mluk:        